name: fsc_management
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  file_picker: ^10.3.7
  flutter_local_notifications: ^19.5.0
  image_picker: ^1.1.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1

dependency_overrides:
  image: 4.5.4
  esc_pos_utils:
    path: third_party/esc_pos_utils

flutter:
  uses-material-design: true
